name: 'direct_js_interop'
version: 0.0.1
description: Concept of interoperability between Dart and JS.
author: Paul Annekov <paul.annekov@gmail.com>
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  browser: any